// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ApiSelect: typeof import('./src/components/core/schema-form/src/components/ApiSelect.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    BasicArrow: typeof import('./src/components/common/basic-arrow/index.vue')['default']
    BasicHelp: typeof import('./src/components/common/basic-help/index.vue')['default']
    BetterScroll: typeof import('./src/components/custom/BetterScroll.vue')['default']
    Button: typeof import('./src/components/common/button/button.vue')['default']
    CountTo: typeof import('./src/components/custom/CountTo.vue')['default']
    DynamicTable: typeof import('./src/components/core/dynamic-table/dynamic-table.vue')['default']
    FormAction: typeof import('./src/components/core/schema-form/src/components/form-action.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    ImageVerify: typeof import('./src/components/custom/ImageVerify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./src/components/core/schema-form/src/schema-form.vue')['default']
    SchemaFormItem: typeof import('./src/components/core/schema-form/src/schema-form-item.vue')['default']
    ToolBar: typeof import('./src/components/core/dynamic-table/components/tool-bar/index.vue')['default']
  }
}

export {}
